Vagrant.configure("2") do |config|
 
config.vm.define "ansible-controller" do |controller|
    controller.vm.hostname = "ansible-controller"
    controller.vm.box = "generic/debian12"
    controller.vm.network "private_network", ip: "192.168.1.3"

  controller.vm.provision "shell", name: "testun", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y software-properties-common
      sudo sudo-add-repository --yes --update ppa:ansible/ansible
      sudo apt-get install -y ansible
    SHELL

    controller.vm.provision "shell", name: "testdeux", inline: <<-SHELL
      sudo apt-get install sshpass
    SHELL
  end

end