#   sudo ansible-galaxy collection install pfsensible.core
Vagrant.configure("2") do |config|
 
  config.vm.define "ansible-controller" do |controller|
    controller.vm.hostname = "ansible-controller"
    controller.vm.box = "generic/debian12"
    controller.vm.network "private_network", ip: "192.168.1.3"


    controller.vm.provision "file", source: "../conf/ansible.cfg", destination: "/home/vagrant/ansible.cfg"
    controller.vm.provision "file", source: "../conf/inventory.ini", destination: "/home/vagrant/inventory.ini"
    controller.vm.provision "file", source: "../conf/desactivation_carte_reseaux.yml", destination: "/home/vagrant/desactivation_carte_reseaux.yml"

    controller.vm.provision "shell", name: "testun", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y software-properties-common
      sudo sudo-add-repository --yes --update ppa:ansible/ansible
      sudo apt-get install -y ansible
      SHELL

    controller.vm.provision "shell", name: "testdeux", inline: <<-SHELL
      sudo apt-get install sshpass
    SHELL

    controller.vm.provision "shell", name: "testdeux", inline: <<-SHELL
      sudo mkdir -p ~/ansible
      sudo mv /home/vagrant/ansible.cfg /home/vagrant/ansible/ansible.cfg
      sudo mv /home/vagrant/inventory.ini /home/vagrant/ansible/inventory.ini
      sudo mv /home/vagrant/desactivation_carte_reseaux.yml /etc/wazuh-indexer/desactivation_carte_reseaux.yml
      cd ~/ansible
      ansible-playbook -i inventory.ini desactivation_carte_reseaux.yml
    SHELL
  end


  # Machine 2 : Debian Test
  config.vm.define "debian-test" do |testvm|
    testvm.vm.hostname = "debian-test"
    testvm.vm.box = "generic/debian12"
    testvm.vm.network "private_network", ip: "192.168.1.4"

    testvm.vm.provision "shell", name: "install_ssh", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y openssh-server
      sudo systemctl enable ssh
      sudo systemctl start ssh
      sudo useradd -m -s /bin/bash ansible
      echo 'ansible:ansible' | sudo chpasswd
      sudo sed -i 's/^#\?PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sudo systemctl restart ssh
      sudo usermod -aG sudo ansible
    SHELL
      
###################################################################################""
#       nano desactivatio_carte_reseaux.yml

#       ---
# - name: Supprimer une ligne spécifique d'un fichier
#   hosts: debian_test
#   become: true

#   tasks:
#     - name: Supprimer toutes les lignes contenant "motclé" dans fichier.txt
#       lineinfile:
#         path: /etc/network/interfaces
#         regexp: 'eth0'
#         state: absent


# - name: Redémarrer le service networking
#   hosts: debian_test
#   become: true

#   tasks:
#     - name: Redémarrer le service networking avec systemd
#       systemd:
#         name: networking
#         state: restarted
#       ignore_errors: yes   # Ignore les erreurs si la commande échoue (utile selon la distro)

#     - name: Vérifier le statut du service networking
#       systemd:
#         name: networking
#         state: started
#     - name: Supprimer une adresse IP de l'interface réseau
#       hosts: debian_test
#       become: true   # Nécessite des privilèges sudo
#       tasks:
#         - name: Supprimer l'adresse IP 10.0.2.15/24 de eth0
#           command: ip addr del 10.0.2.15/24 dev eth0

#     nano ansible.cfg
#     [defaults]
# inventory = inventory.ini
# host_key_checking = False
# retry_files_enabled = False
# timeout = 30


# nano inventory.ini
# [debian_test]
# 192.168.1.4 ansible_user=ansible ansible_password=ansible ansible_become_password=ansible ansible_ssh_common_args='-o StrictHostKeyC>


# ansible-playbook -i inventory.ini desactivation_carte_reseaux.yml


  end

end