#   sudo ansible-galaxy collection install pfsensible.core
Vagrant.configure("2") do |config|
 
  config.vm.define "ansible-controller" do |controller|
    controller.vm.hostname = "ansible-controller"
    controller.vm.box = "generic/debian12"
    controller.vm.network "private_network", ip: "192.168.1.3"

    controller.vm.provision "shell", name: "testun", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y software-properties-common
      sudo sudo-add-repository --yes --update ppa:ansible/ansible
      sudo apt-get install -y ansible
      SHELL

    controller.vm.provision "shell", name: "testdeux", inline: <<-SHELL
      sudo apt-get install sshpass
    SHELL
  end


  # Machine 2 : Debian Test
  config.vm.define "debian-test" do |testvm|
    testvm.vm.hostname = "debian-test"
    testvm.vm.box = "generic/debian12"
    testvm.vm.network "private_network", ip: "192.168.1.4"

    testvm.vm.provision "shell", name: "install_ssh", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y openssh-server
      sudo systemctl enable ssh
      sudo systemctl start ssh

      # Ajout d'un utilisateur ansible avec accès SSH par mot de passe
      sudo useradd -m -s /bin/bash ansible
      echo 'ansible:ansible' | sudo chpasswd

      # Autoriser la connexion par mot de passe (utile pour les premiers tests Ansible)
      sudo sed -i 's/^#\?PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
      sudo systemctl restart ssh
    SHELL
  end

end