- name: recuperer le hostname
  ansible.builtin.shell: hostname
  register: hostname_

- name: Get agent wazuh
  ansible.builtin.shell: wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.10.1-1_amd64.deb && sudo WAZUH_MANAGER='192.168.1.2' WAZUH_AGENT_NAME='{{ hostname_.stdout }}' dpkg -i ./wazuh-agent_4.10.1-1_amd64.deb
  become: true

- name: start service  wazuh and enable
  ansible.builtin.shell: sudo systemctl daemon-reload && sudo systemctl enable wazuh-agent && sudo systemctl start wazuh-agent
  become: true