all:
  children:
    soc:
      children:
        soc_siem:
          hosts:
            wazuh:
              ansible_host: 192.168.1.2
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_connection: ssh
    domaine1:
      children:
        domaine1_windows:
          hosts:
            dc01:
              ansible_host: 10.10.1.2
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_connection: winrm
              ansible_winrm_transport: basic
              ansible_winrm_server_cert_validation: ignore
            file_srv:
              ansible_host: 10.10.1.3
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_connection: winrm
              ansible_winrm_transport: basic
              ansible_winrm_server_cert_validation: ignore
        domaine1_linux:
          hosts:
            debian:
              ansible_host: 10.10.1.4
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_connection: ssh
            suricata:
              ansible_host: 10.10.1.5
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_connection: ssh
    domaine2:
      children:
        domaine2_windows:
          hosts:
            dc02:
              ansible_host: 10.10.2.2
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_connection: winrm
              ansible_winrm_transport: basic
              ansible_winrm_server_cert_validation: ignore
            iis:
              ansible_host: 10.10.2.3
              ansible_user: vagrant
              ansible_password: vagrant
              ansible_connection: winrm
              ansible_winrm_transport: basic
              ansible_winrm_server_cert_validation: ignore
