Vagrant.configure("2") do |config|
    config.vm.define "pfsense" do |pfsense|
        pfsense.vm.box = "kennyl/pfsense"
        pfsense.vm.box_version = "2.4.0"

        pfsense.vm.synced_folder ".", "/vagrant", disabled: true

        pfsense.vm.network "private_network", ip: "192.168.1.1", name: "vboxnet5" # interface SOC
        pfsense.vm.network "private_network", ip: "192.168.2.1", name: "vboxnet4" # Interface Red Team
        pfsense.vm.network "private_network", ip: "10.10.0.1", name: "vboxnet3"   # Interface Poste client
        pfsense.vm.network "private_network", ip: "10.10.1.1", name: "vboxnet1"   # Interface Domaine 1
        pfsense.vm.network "private_network", ip: "10.10.2.1", name: "vboxnet2"   # Interface Domaine 2

        

        pfsense.vm.network "forwarded_port", guest: 443, host: 4343



        pfsense.vm.provider "virtualbox" do |vb|
            vb.name = "pfsense"
            vb.memory = "1024"
            vb.cpus = 2
        end
    end
end