Vagrant.configure("2") do |config|
    config.vm.define "pfsense" do |pfsense|
        pfsense.vm.box = "kennyl/pfsense"
        pfsense.vm.box_version = "2.4.0"
        pfsense.vm.synced_folder ".", "/vagrant", disabled: true

        pfsense.vm.network "private_network", ip: "192.168.1.2" # interface SOC
        pfsense.vm.network "private_network", ip: "192.168.2.2" # Interface Red Team
        pfsense.vm.network "private_network", ip: "10.10.0.2"   # Interface Poste client
        pfsense.vm.network "private_network", ip: "10.10.1.2"   # Interface Domaine 1
        pfsense.vm.network "private_network", ip: "10.10.2.2"   # Interface Domaine 2

        
        pfsense.vm.network "forwarded_port", guest: 80, host: 1234
        pfsense.vm.network "forwarded_port", guest: 443, host: 4342

        pfsense.vm.provider "virtualbox" do |vb|
            vb.memory = "1024"
            vb.cpus = 2
        end
    end
end