- name: Récupérer le hostname
  ansible.windows.win_shell: |
    $ComputerName = $env:COMPUTERNAME
    $RandomNumber = Get-Random -Minimum 1000 -Maximum 9999
    $WazuhAgentName = "$ComputerName-$RandomNumber"
    Write-Output $WazuhAgentName
  register: hostname_

- name: Debug hostname récupéré
  debug:
    msg: "Nom de l'agent Wazuh: {{ hostname_.stdout }}"

- name: Configuration de l'agent wazuh
  ansible.windows.win_shell: |
    Start-Process msiexec.exe -ArgumentList "/i `"$env:TEMP\wazuh-agent.msi`" /q WAZUH_MANAGER=192.168.1.2 WAZUH_AGENT_GROUP=default WAZUH_AGENT_NAME={{ hostname_.stdout }}" -Wait
  
- name: Démarrer le service Wazuh
  ansible.windows.win_shell: NET START Wazuh
