dc02: 
  ansible_host: 10.10.2.2
  ansible_user: vagrant
  ansible_password: vagrant
  ansible_connection: winrm
  ansible_winrm_transport: basic
  ansible_winrm_server_cert_validation: ignore


iis:
  ansible_host: 10.10.2.3
  ansible_user: vagrant
  ansible_password: vagrant
  ansible_connection: winrm
  ansible_winrm_transport: basic
  ansible_winrm_server_cert_validation: ignore


windows:
  ansible_host: 10.10.2.4
  ansible_user: vagrant
  ansible_password: vagrant
  ansible_connection: winrm
  ansible_winrm_transport: basic
  ansible_winrm_server_cert_validation: ignore