- name: Activation des journaux d'evenements nécaissaire
  win_shell: |
    PowerShell -ExecutionPolicy Bypass -File C:\Users\vagrant\AppData\Local\Temp\Configure-Channel.ps1
  become_user: 'Administrator'
  become_method: runas
  become: yes
  