- name: Get package wazuh
  ansible.builtin.shell: curl -sO https://packages.wazuh.com/4.10/wazuh-install.sh
  become: true

- name: install wazuh
  ansible.builtin.shell: /bin/bash ./wazuh-install.sh -a
  become: true

- name: get password admin
  ansible.builtin.shell: sudo tar -xvf wazuh-install-files.tar && cd wazuh-install-files/ && sudo cat wazuh-passwords.txt
  become: true


- name: Télécharger et exécuter le script Wazuh-SOCFortress
  ansible.builtin.shell: |
    curl -so /tmp/wazuh_socfortress_rules.sh https://raw.githubusercontent.com/socfortress/Wazuh-Rules/main/wazuh_socfortress_rules.sh && \
    bash /tmp/wazuh_socfortress_rules.sh -y
  args:
    executable: /bin/bash
  become: true

- name: Ajouter un bloc après une ligne spécifique pour configuration de récéption des logs du pfsense via syslog
  ansible.builtin.blockinfile:
    path: /var/ossec/etc/ossec.conf
    block: |
      <remote>
        <connection>syslog</connection>
        <port>514</port>
        <protocol>udp</protocol>
        <allowed-ips>192.168.1.1</allowed-ips>
        <local_ip>192.168.1.2</local_ip>
      </remote>
      <remote>
        <connection>syslog</connection>
        <port>514</port>
        <protocol>tcp</protocol>
        <allowed-ips>192.168.1.1</allowed-ips>
        <local_ip>192.168.1.2</local_ip>
      </remote>
    insertafter: '</remote>'
    marker: ""
  become: true 

- name: reboot du service wazuh
  ansible.builtin.shell: sudo systemctl restart wazuh-manager
  become: true