- name: Get package wazuh
  ansible.builtin.shell: curl -sO https://packages.wazuh.com/4.10/wazuh-install.sh
  become: true

- name: install wazuh
  ansible.builtin.shell: /bin/bash ./wazuh-install.sh -a
  become: true

- name: get password admin
  ansible.builtin.shell: sudo tar -xvf wazuh-install-files.tar && cd wazuh-install-files/ && sudo cat wazuh-passwords.txt
  become: true


- name: Télécharger et exécuter le script Wazuh-SOCFortress
  ansible.builtin.shell: |
    curl -so /tmp/wazuh_socfortress_rules.sh https://raw.githubusercontent.com/socfortress/Wazuh-Rules/main/wazuh_socfortress_rules.sh && \
    bash /tmp/wazuh_socfortress_rules.sh -y
  args:
    executable: /bin/bash
  become: true