- name: Création des groupes gloabaux
  microsoft.ad.group:
    name: "GG_{{ item }}"
    scope: global
    path: "OU=GG,OU=Groupes,DC=irma,DC=local"
    state: present
  loop: 
    - Direction
    - RH
    - IT
    - Finance

# domaine locale

- name: Création d'un groupe globale direction en ecriture
  microsoft.ad.group:
    name: "GDL_{{ item }}_RW"
    scope: domainlocal
    path: "OU=GDL,OU=Groupes,DC=irma,DC=local"
    state: present
  loop: 
    - Direction
    - RH
    - IT
    - Finance

- name: Création d'un groupe globale direction en lecture
  microsoft.ad.group:
    name: "GDL_{{ item }}_RO"
    scope: domainlocal
    path: "OU=GDL,OU=Groupes,DC=irma,DC=local"
    state: present
  loop: 
    - Direction
    - RH
    - IT
    - Finance

