- name: Importation de listes d'utiliateurs 
  include_vars: 
    file: users_list.yml
  
- name: Création d'un utilisateur kerberoastable
  microsoft.ad.user:
    identity: bob
    firstname: Bob
    surname: Smith
    password: B0bP4ssw0rd
    state: present
    path: ou=Utilisateurs,dc=irma,dc=local
    spn:
      add:
        - FAKE/SERVICE


   
- name: Création de l'utilisateur 
  microsoft.ad.user:
    identity: "{{ item.identity }}"
    firstname: "{{ item.firstname }}"
    surname: "{{ item.surname }}"
    password: "{{ item.password }}"
    path: "ou={{ item.group }},ou=Utilisateurs,dc=irma,dc=local"

    state: present
  loop: "{{ users }}" 

