# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # DOMAINE 1 
  config.vm.define "dc01" do|dc01|
    dc01.vm.box = "jborean93/WindowsServer2022"
    dc01.vm.box_version = "1.2.0"
    
    dc01.vm.hostname = "dc01"
    dc01.vm.guest = :windows
    dc01.winrm.transport = :ssl
    dc01.vm.network "private_network", ip: "10.10.1.2", virtualbox__intnet: "vboxnet1"
    dc01.vm.boot_timeout = 400
    dc01.winrm.basic_auth_only = true
    dc01.winrm.ssl_peer_verification = false # ajout suite a l'erruer ssl_peer_verification 
    
    dc01.vm.provider "virtualbox" do |vb|
      vb.name = "DC01"
      vb.memory = 3072 # 2 Go de RAM
      vb.cpus = 3 # 2 processeurs
    end

    dc01.vm.provision "shell", inline: 'Invoke-WebRequest -Uri "https://packages.wazuh.com/4.x/windows/wazuh-agent-4.10.1-1.msi" -OutFile "$env:TEMP\wazuh-agent.msi"'

  end

  config.vm.define "file_srv" do|file_srv|
    file_srv.vm.box = "jborean93/WindowsServer2022"
    file_srv.vm.box_version = "1.2.0"

    file_srv.vm.hostname = "FileSrv"
    file_srv.vm.network "private_network", ip: "10.10.1.3", virtualbox__intnet: "vboxnet1"
    file_srv.vm.guest = :windows
    file_srv.winrm.transport = :ssl
    file_srv.winrm.basic_auth_only = true
    file_srv.vm.boot_timeout = 400
    file_srv.winrm.ssl_peer_verification = false # ajout suite a l'erruer ssl_peer_verification 

    file_srv.vm.provider "virtualbox" do |vb|
      vb.name = "FILE_SRV"
      vb.memory = 3072 # 2 Go de RAM
      vb.cpus = 3 # 2 processeurs
    end
    
    file_srv.vm.provision "shell", inline: 'Invoke-WebRequest -Uri "https://packages.wazuh.com/4.x/windows/wazuh-agent-4.10.1-1.msi" -OutFile "$env:TEMP\wazuh-agent.msi"'
    

  end
  
  config.vm.define "debian" do|debian|
    debian.vm.box = "generic/debian12"
    debian.vm.hostname = "debian"
    debian.vm.network "private_network", ip: "10.10.1.4", virtualbox__intnet: "vboxnet1"

    debian.vm.provider "virtualbox" do |vb|
      vb.name = "debian"
      vb.memory = 2048 # 2 Go de RAM
      vb.cpus = 1 # 2 processeurs
      end

    debian.vm.provision "shell", inline: "wget https://packages.wazuh.com/4.x/apt/pool/main/w/wazuh-agent/wazuh-agent_4.10.1-1_amd64.deb -O /home/vagrant/wazuh-agent_4.10.1-1_amd64.deb"
    debian.vm.provision "file", source: "Install-DVWA.sh", destination: "/home/vagrant/Install-DVWA.sh"

    debian.vm.provision "shell",name:"installation_apache" , inline: <<-SHELL
      echo "vagrant"|sudo -S apt update -y 
      sudo apt install apache2 -y 
      sudo systemctl enable apache2.service
    SHELL
    
    debian.vm.provision "shell",name:"installation_dvwa", inline: <<-SHELL
      sudo chmod +x Install-DVWA.sh
      sudo ./Install-DVWA.sh
    SHELL

    debian.vm.provision "shell",name:"configuration_carte_reseaux", inline: <<-SHELL
      echo "
      source /etc/network/interfaces.d/*
      auto eth1
      iface eth1 inet static
        address 10.10.1.4
        netmask 255.255.255.0
        gateway 10.10.1.1
        dns-nameservers 8.8.8.8
      " | sudo tee /etc/network/interfaces
        sudo reboot
    SHELL



  end
end
