Vagrant.configure("2") do |config|
  config.vm.define "wazuhserver" do |wazuhserver|
    wazuhserver.vm.box = "generic/debian12"
    wazuhserver.vm.hostname = "wazuhserver"
    wazuhserver.vm.network "private_network", type: "static", ip: "192.168.1.2", virtualbox__intnet:"vboxnet5"
    wazuhserver.vm.provider "virtualbox" do |vb|
      vb.memory = "4096"
      vb.cpus = 3
    end

    wazuhserver.vm.provision "shell", name: "add gateway /etc/network/interfaces", inline: <<-SHELL
    echo "
      source /etc/network/interfaces.d/*
      auto eth1
      iface eth1 inet static
        address 192.168.1.2
        netmask 255.255.255.0
        gateway 192.168.1.1
      " | sudo tee /etc/network/interfaces
        sudo reboot
      SHELL
  end
end