---
# tasks file for ansible-tmux
- name: Copy main tmux config
  copy:
    src: tmux.conf
    dest: "{{ansible_env.HOME}}/.tmux.conf"

- name: Copy colors
  copy:
    src: colors.tmuxtheme
    dest: "{{ansible_env.HOME}}/.colors.tmuxtheme"


