Vagrant.configure("2") do |config|

  config.vm.define "dc02" do|dc02|
    dc02.vm.box = "jborean93/WindowsServer2016"
    dc02.vm.box_version = "1.2.0"

    
    dc02.vm.hostname = "dc02"
    dc02.vm.guest = :windows
    dc02.winrm.transport = :ssl
    dc02.vm.network "private_network", ip: "10.10.2.2", virtualbox__intnet: "vboxnet2"
    dc02.winrm.basic_auth_only = true
    dc02.vm.boot_timeout = 400
    dc02.winrm.ssl_peer_verification = false # ajout suite a l'erruer ssl_peer_verification 
    
    
    dc02.vm.provider "virtualbox" do |vb|
      vb.name = "DC02"
      vb.memory = 2048 # 2 Go de RAM
      vb.cpus = 2 # 2 processeurs
    end

    dc02.vm.provision :ansible do |ansible|
      ansible.limit = 'all'
      ansible.playbook = 'ansible/playbook.yml'
      ansible.verbose =  true
      ansible.limit = "dc02"  # Exécute seulement dc02
      ansible.host_vars = {
      "dc02" => {"ansible_winrm_server_cert_validation" => "ignore"}
    }
    end 
  end

  config.vm.define "iis" do|iis|
    iis.vm.box = "jborean93/WindowsServer2016"
    iis.vm.box_version = "1.2.0"
    iis.vm.hostname = "IIS16"
    iis.vm.network "private_network", ip: "10.10.2.3", virtualbox__intnet: "vboxnet2"
    iis.vm.guest = :windows
    iis.winrm.transport = :ssl
    iis.vm.boot_timeout = 400
    iis.winrm.ssl_peer_verification = false # ajout suite a l'erruer ssl_peer_verification 

    iis.vm.provider "virtualbox" do |vb|
      vb.name = "IIS16"
      vb.memory = 2048 # 2 Go de RAM
      vb.cpus = 2 # 2 processeurs
    end


    iis.vm.provision :ansible do |ansible|
      ansible.limit = 'all'
      ansible.playbook = 'ansible/playbook.yml'
      ansible.verbose =  true
      ansible.limit = "iis"  # Exécute seulement iis
      ansible.host_vars = {
      "iis" => {"ansible_winrm_server_cert_validation" => "ignore"}
    }
    end 
  end
  
  config.vm.define "windows" do|windows|
    windows.vm.box = "mrlesmithjr/windows10"
    windows.vm.box_version = "1580850073"
    windows.vm.hostname = "windows"

    windows.vm.network "private_network", ip: "10.10.2.4", virtualbox__intnet: "vboxnet2"
    windows.vm.boot_timeout = 400
    windows.vm.guest = :windows
    windows.winrm.transport = :ssl
    windows.winrm.basic_auth_only = true
    windows.winrm.ssl_peer_verification = false # ajout suite a l'erruer ssl_peer_verification 

    windows.vm.provider "virtualbox" do |vb|
      vb.name = "windows10"
      vb.memory = 1024 # 2 Go de RAM
      vb.cpus = 2 # 2 processeurs
    end

    windows.vm.provision :ansible do |ansible|
        ansible.limit = 'all'
        ansible.playbook = 'ansible/playbook.yml'
        ansible.verbose =  true
        ansible.limit = "windows"  # Exécute seulement windows
        ansible.host_vars = {
        "windows" => {"ansible_winrm_server_cert_validation" => "ignore"}
      }
    end 
  end 
end

