Vagrant.configure("2") do |config|

  config.vm.define "dc02" do|dc02|
    dc02.vm.box = "jborean93/WindowsServer2016"
    dc02.vm.box_version = "1.2.0"

    
    dc02.vm.hostname = "dc02"
    dc02.vm.guest = :windows
    dc02.winrm.transport = :ssl
    dc02.vm.network "private_network", ip: "10.10.2.2", virtualbox__intnet: "vboxnet2"
    dc02.winrm.basic_auth_only = true
    dc02.vm.boot_timeout = 400
    dc02.winrm.ssl_peer_verification = false # ajout suite a l'erruer ssl_peer_verification 
    
    
    dc02.vm.provider "virtualbox" do |vb|
      vb.name = "DC02"
      vb.memory = 3072 # 2 Go de RAM
      vb.cpus = 3 # 2 processeurs
    end

    dc02.vm.provision "shell", inline: 'Invoke-WebRequest -Uri "https://packages.wazuh.com/4.x/windows/wazuh-agent-4.8.0-1.msi" -OutFile "$env:TEMP\wazuh-agent.msi"'


  end

  config.vm.define "iis" do|iis|
    iis.vm.box = "jborean93/WindowsServer2016"
    iis.vm.box_version = "1.2.0"
    iis.vm.hostname = "IIS16"
    iis.vm.network "private_network", ip: "10.10.2.3", virtualbox__intnet: "vboxnet2"
    iis.vm.guest = :windows
    iis.winrm.transport = :ssl
    iis.vm.boot_timeout = 400
    iis.winrm.ssl_peer_verification = false # ajout suite a l'erruer ssl_peer_verification 

    iis.vm.provider "virtualbox" do |vb|
      vb.name = "IIS16"
      vb.memory = 3072 # 2 Go de RAM
      vb.cpus = 3 # 2 processeurs
    end

    iis.vm.provision "shell", inline: 'Invoke-WebRequest -Uri "https://packages.wazuh.com/4.x/windows/wazuh-agent-4.8.0-1.msi" -OutFile "$env:TEMP\wazuh-agent.msi"'
  end
  
end

